/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/aula-virtual`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil/administradores`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil/auditoria`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/aula-virtual`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `/roles/superadmin-movil/administradores`; params?: Router.UnknownOutputParams; } | { pathname: `/roles/superadmin-movil/auditoria`; params?: Router.UnknownOutputParams; } | { pathname: `/roles/superadmin-movil/configuracion`; params?: Router.UnknownOutputParams; } | { pathname: `/roles/superadmin-movil`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/aula-virtual${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | `/roles/superadmin-movil/administradores${`?${string}` | `#${string}` | ''}` | `/roles/superadmin-movil/auditoria${`?${string}` | `#${string}` | ''}` | `/roles/superadmin-movil/configuracion${`?${string}` | `#${string}` | ''}` | `/roles/superadmin-movil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/aula-virtual`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil/administradores`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil/auditoria`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/roles/superadmin-movil`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
